name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8
        # Install other dependencies from setup.py
        pip3 install .
    - name: Lint with flake8
      run: |
        echo "Linting rcar_flash directory"
        flake8 ./rcar_flash --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./rcar_flash --count --max-complexity=12 --max-line-length=120 --statistics
